# Generated by Django 3.1.7 on 2021-04-08 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210408_1752'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='details',
            new_name='user',
        ),
    ]
